version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: seid_cia_db
      MYSQL_USER: root
      MYSQL_PASSWORD: SuperM45t3r?   
      MYSQL_ROOT_PASSWORD: password
      
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/seid_cia_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SuperM45t3r?   

volumes:
  mysql-data:
