spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://172.30.89.161:3306/seid_cia_db?createDatabaseIfNotExist=true
    username: admin
    password: senha123
    # driver-class-name: com.mysql.cj.jdbc.Driver
  # liquibase:
  #   enabled: false
  # flyway:
  #   enabled: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      file-size-threshold: 2KB
      max-request-size: 25MB

root:
  dir: /tmp/database
file:
  dir: autistic-files
